### ISSUE TITLE
Get weather from external API and return it to client

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#38]
- Upon receiving the get request from the client, the back-end will get the current weather data from the external weather API, save it in its database and pass the data on to the client

Estimated time: 4h
This task is part of user story #26

**Comment by Thahit** [comment]
In the beginning of the game, the weather is safed, but if it changes durring the game, the changes don't apply to the game(otherwise we would have too many api calls(they are limited))

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/0d621e75d7f1b2fc2824d3465f4d638904481e42
