### ISSUE TITLE
Ending the game when player's or opponent's health reaches nil

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#40]
- When an active player playing the game reaches 0 health points, the game instance is stopped and the final stats are returned to the client at its next /games/{gameId} GET request

Estimated time: 3h
This task is part of user story #24

**Comment by Thahit** [comment]
no multiplayer

**Comment by Thahit** [comment]
now deletes game when leaving/losing
https://github.com/sopra-fs21-group-10/td-server/commit/f5ae81890511763f636d900f6f0a554a44f86b64 (=test)
