### ISSUE TITLE
Awarding passive income

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#42]
- During the game, at the end of each preparation phase, the active players will receive interest based on their wealth.
- At the end of each preparation phase, the player profiles will be updated with the new amount of gold
- The updated value will be returned to the client during its next /games/{gameId} GET request

Estimated time: 4h
This task is part of user story #22

**Comment by Thahit** [comment]
it is debatable when to give the interest, and weather to return the gold count, but interest exists
a2a1b25
