### ISSUE TITLE
Upgrade and sale of towers

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#45]
- When a PATCH request is sent to /games/{gameId)/{token} with the purpose of selling a tower, the tower will be deleted from the game instance and the player's gold balance will be updated accordingly.
- When a PATCH request is sent to /games/{gameId)/{token} with the purpose of upgrading a tower, the tower will be updated in the game instance and the player's gold balance will be reduced accordingly.
- The updated stats will be returned to the client during the next /games/{gameId} GET update

Estimated time: 4h
This task is part of user story #19

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/c9cea32910b8a0872fb207da25a54d117124e998
