### ISSUE TITLE
Spawning of minions

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#46]
- At the start of each battle phase, based on the round number, an ever increasing amount of minions will be added to the game instance.
- Once a minion reaches the end of the pathway, the client will send a PATCH /games/{gameId)/{token} request, and the minion will be removed from the game instance

Estimated time: 10h
This task is part of user story #16

**Comment by Thahit** [comment]
which minions spawn per wave

**Comment by Thahit** [comment]
29e2684
list of minions to get spawned
