### ISSUE TITLE
using the shop during preparation phase

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#47]
- Update the game and user instances based on the request received from the client
- Return the updated stats and gold balance at the next /games/{gameId} update
- Return an error message if client tries to access the shop during battle phase or does not have enough gold to make the requested purchase

Estimated time: 7h
This task is part of user story #15

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/650640dfdb0407692b2d1552b87030694803df7a
