### ISSUE TITLE
Creating the playing field

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#49]
- When a game is started, a game instance is created and initialized with a random (n x m) playing field
- When receiving a GET /games/{gameId} request, the playing field is returned to the client

Estimated time: 10h
This task is part of user story #11

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/0d621e75d7f1b2fc2824d3465f4d638904481e42
