### ISSUE TITLE
Starting a multiplayer game

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#50]
- When the server receives a valid POST /games request, a new game instance and player instances will be created and stored in the database.
- When the server receives a GET /lobbies request, it will return all info about the open lobbies.
- Upon creation of a new game instance, the server returns the gameID and game information to the client.

Estimated time: 10h
This task is part of user story #11

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/0d621e75d7f1b2fc2824d3465f4d638904481e42
