### ISSUE TITLE
Starting a single player game

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#51]
- When the server receives a valid POST /games request, a new game instance and player instance will be created and stored in the database.
- Upon creation of a new game instance, the server returns the gameID and game information to the client.

Estimated time: 2h
This task is part of user story #10

**Comment by Thahit** [comment]
should work in theory,  the specific  game information(like at how much hp you start, is jet to be decided)

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/0d621e75d7f1b2fc2824d3465f4d638904481e42
