### ISSUE TITLE
Buying and placing towers/minions

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#52]
- Upon receiving a PATCH /games/{gameId)/{token} purchase request during the preparation phase from the client, it is checked whether the player has sufficient funds for the requested purchase. In case of sufficient funds, a confirmation status is sent to the client and the purchase is saved to the game and player instances in the database. In case of insufficient funds, an error status code will be sent.
- In case of an enemy minion purchase, the respective number of minions is added to the next wave of the battle phase to the targeted opponent's player instance.
- The client receives the updated stats via the next GET /games/{gameId} request

Estimated time: 4h
This task is part of user story #18

**Comment by Thahit** [comment]
towers are there

**Comment by Thahit** [comment]
post /games/towers/{token} = place towers
post /games/minions/{gameId}/{token} = buying minions

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/70f6065f86d1b5bc01163ea8594fecaf6ab5257d
now shows extraMinions in map
