### ISSUE TITLE
update user settings

### ISSUE THREAD

**Issue by bzns** [sopra-fs21-group-10/td-server#53]
- When a valid PATCH /users/{userid}/{token} request is received, the requested username is checked for duplicates in the database, and the existence of the requested location is verified. If the username is unique and the location exists, the player instance is updated in the database with the new data and a confirmation status is returned. If the username is a duplicate or if the requested location cannot be found, a corresponding error message is returned.

Estimated time: 2h
This task is part of user story #9

**Comment by Thahit** [comment]
https://github.com/sopra-fs21-group-10/td-server/commit/44e5e9662f66b36d7123641a9e67af9a2c9c6c27
